site_name: Colabfold on OSCAR
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Building from Docker: docker.md
  - Local MSA Generation: msas.md
theme:
  name: readthedocs
  logo: img/oscarcolabfold.png
